# Generated by Django 5.1 on 2024-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookinfo_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
